<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Success                        Failure</name>
   <tag></tag>
   <elementGuidId>860c34be-5919-413f-8b1c-153ebdeb709c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>select[name=&quot;merchantStatus&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@name='merchantStatus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cf5fee23-8ec0-4ee7-8565-d8e1741f98b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>merchantStatus</value>
      <webElementGuid>15816049-66b4-4973-a708-e6415c4ca811</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        Success
                        Failure
                    </value>
      <webElementGuid>444c3815-9984-4a6d-826b-f2ac444975c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wrap&quot;)/div[@class=&quot;container&quot;]/form[@class=&quot;form-horizontal&quot;]/div[@class=&quot;form-group&quot;]/div[@class=&quot;col-sm-10&quot;]/select[1]</value>
      <webElementGuid>f8394a66-bb05-4a75-b414-e59cea10990e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@name='merchantStatus']</value>
      <webElementGuid>f6ec4c1c-adab-4edd-b006-c67b23c94c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='wrap']/div[2]/form/div[2]/div/select</value>
      <webElementGuid>2d02e4c1-11be-4485-8c48-c3dc72c85f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Scenario to Simulate'])[1]/following::select[1]</value>
      <webElementGuid>ea6d2757-bb98-45bc-bfb1-30d95d30a323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Id'])[1]/following::select[1]</value>
      <webElementGuid>9a6f44a9-6de3-4fc0-85ce-f52e0edba71b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pay'])[1]/preceding::select[1]</value>
      <webElementGuid>eb73afe7-7a64-43c1-bd89-970ebcea53f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>3cbcb2e8-e3df-40e7-b3d2-aa15d7287583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'merchantStatus' and (text() = '
                        Success
                        Failure
                    ' or . = '
                        Success
                        Failure
                    ')]</value>
      <webElementGuid>73488236-a59b-45c1-bb8a-dc7745c7a66a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
